// src/components/Farm/farmData.js

// Major export ports coordinates
export const MAJOR_PORTS = {
  mumbai: { lat: 19.0760, lng: 72.8777, name: "Mumbai Port (JNPT)" },
  mundra: { lat: 22.6989, lng: 69.7581, name: "Mundra Port" },
  chennai: { lat: 13.0837, lng: 80.2700, name: "Chennai Port" },
  kochi: { lat: 9.9312, lng: 76.2673, name: "Cochin Port" },
  dubai: { lat: 25.2048, lng: 55.2708, name: "Dubai (UAE)" },
  singapore: { lat: 1.3521, lng: 103.8198, name: "Singapore" },
  rotterdam: { lat: 51.9244, lng: 4.4777, name: "Rotterdam (EU)" },
  london: { lat: 51.5074, lng: -0.1278, name: "London (UK)" },
  newyork: { lat: 40.7128, lng: -74.0060, name: "New York (USA)" },
  tokyo: { lat: 35.6762, lng: 139.6503, name: "Tokyo (Japan)" }
};

// Enhanced farm data with 14 premium farms
export const ENHANCED_FARMS = [
  {
    id: 1,
    name: "Golden Pomegranate Estate",
    location: "Jeewana, Jalore District, Rajasthan",
    farmer: "Ramesh Kumar Sharma",
    crops: [
      { name: "Premium Pomegranate", price: "$8.50 - $12.50/kg", grade: "A++" },
      { name: "Royal Cumin", price: "$6.80 - $9.20/kg", grade: "A+" },
      { name: "Gold Coriander", price: "$5.50 - $8.00/kg", grade: "A+" }
    ],
    area: "45 acres",
    established: "2018",
    certifications: ["Organic", "ISO 22000", "HACCP", "GlobalGAP", "Fair Trade", "EU Organic"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Optimal growing conditions detected. Harvest predicted in 15 days with 98% export readiness. AI recommends immediate premium market placement.",
    exportReadiness: "Ready for International Markets",
    monthlyProduction: "2.5 tons",
    annualRevenue: "$425,000",
    sustainabilityScore: 94,
    waterUsageEfficiency: "92%",
    carbonFootprint: "Low",
    marketDemand: "High",
    priceRange: "$8.50 - $12.50/kg",
    weatherCondition: "sunny",
    qualityTrend: [92, 94, 93, 95, 96, 94, 95],
    soilPH: 6.8,
    rainfall: 45,
    premiumLevel: "Diamond",
    exportMarkets: ["UAE", "UK", "USA", "Germany", "France"],
    nearestPort: "Mundra Port",
    shippingRoute: [[25.35, 72.62], [22.6989, 69.7581]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$150,000",
      expectedReturn: "$425,000",
      profitMargin: "183%",
      paybackPeriod: "4-6 months",
      annualROI: "280%"
    },
    farmerControls: {
      irrigation: { status: "Active", schedule: "Every 48h", automation: "85%" },
      pestControl: { status: "Monitoring", lastSpray: "3 days ago", method: "Organic" },
      harvesting: { status: "Scheduled", date: "15 days", equipment: "Ready" },
      qualityCheck: { status: "Daily", lastScore: "96%", nextCheck: "Tomorrow" }
    },
    lat: 25.35,
    lng: 72.62,
    region: "rajasthan"
  },
  {
    id: 2,
    name: "Royal Spice Gardens",
    location: "Bhinmal, Rajasthan",
    farmer: "Suresh Patel",
    crops: [
      { name: "Premium Red Chili", price: "$6.50 - $9.80/kg", grade: "A+" },
      { name: "Golden Turmeric", price: "$5.20 - $7.50/kg", grade: "A" },
      { name: "Royal Fenugreek", price: "$4.80 - $6.90/kg", grade: "A" }
    ],
    area: "38 acres",
    established: "2019",
    certifications: ["ISO 22000", "HACCP", "USDA Organic", "Halal"],
    status: "warning",
    exportGrade: "Premium A+",
    aiInsights: "Slight water stress detected. AI suggests 10% increase in irrigation for optimal quality. Export potential remains high.",
    exportReadiness: "Monitoring – 92% Export Ready",
    monthlyProduction: "2.1 tons",
    annualRevenue: "$310,000",
    sustainabilityScore: 88,
    waterUsageEfficiency: "86%",
    carbonFootprint: "Medium",
    marketDemand: "High",
    priceRange: "$6.50 - $9.80/kg",
    weatherCondition: "sunny",
    qualityTrend: [90, 88, 87, 89, 88, 86, 88],
    soilPH: 7.1,
    rainfall: 38,
    premiumLevel: "Platinum",
    exportMarkets: ["UAE", "Singapore", "Malaysia", "Saudi Arabia"],
    nearestPort: "Mundra Port",
    shippingRoute: [[25.01, 72.27], [22.6989, 69.7581]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$125,000",
      expectedReturn: "$310,000",
      profitMargin: "148%",
      paybackPeriod: "5-7 months",
      annualROI: "248%"
    },
    farmerControls: {
      irrigation: { status: "Optimizing", schedule: "Every 72h", automation: "70%" },
      pestControl: { status: "Active", lastSpray: "2 days ago", method: "Biological" },
      harvesting: { status: "Planning", date: "20 days", equipment: "Preparing" },
      qualityCheck: { status: "Daily", lastScore: "88%", nextCheck: "Today" }
    },
    lat: 25.01,
    lng: 72.27,
    region: "rajasthan"
  },
  {
    id: 3,
    name: "Imperial Farmlands",
    location: "Kawtra, Jalore District, Rajasthan",
    farmer: "Mohan Singh Rajput",
    crops: [
      { name: "Royal Pomegranate", price: "$12.00 - $18.00/kg", grade: "World Class" },
      { name: "Premium Cumin", price: "$7.50 - $10.50/kg", grade: "A++" },
      { name: "Golden Mustard", price: "$4.50 - $6.80/kg", grade: "A+" }
    ],
    area: "52 acres",
    established: "2017",
    certifications: ["Organic", "EU Organic", "USDA", "Fair Trade", "Kosher"],
    status: "healthy",
    exportGrade: "World Class",
    aiInsights: "Exceptional color and oil content detected. Ideal for premium markets. AI predicts record-breaking harvest.",
    exportReadiness: "Elite Export Ready - 99%",
    monthlyProduction: "3.0 tons",
    annualRevenue: "$560,000",
    sustainabilityScore: 91,
    waterUsageEfficiency: "89%",
    carbonFootprint: "Low",
    marketDemand: "Very High",
    priceRange: "$12.00 - $18.00/kg",
    weatherCondition: "sunny",
    qualityTrend: [92, 93, 94, 95, 96, 95, 96],
    soilPH: 6.9,
    rainfall: 52,
    premiumLevel: "Diamond",
    exportMarkets: ["USA", "UK", "Japan", "France", "Switzerland"],
    nearestPort: "Mundra Port",
    shippingRoute: [[25.37, 72.52], [22.6989, 69.7581]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$200,000",
      expectedReturn: "$560,000",
      profitMargin: "180%",
      paybackPeriod: "4-5 months",
      annualROI: "280%"
    },
    farmerControls: {
      irrigation: { status: "Optimal", schedule: "Every 48h", automation: "95%" },
      pestControl: { status: "Preventive", lastSpray: "5 days ago", method: "Natural" },
      harvesting: { status: "Ready", date: "12 days", equipment: "Advanced" },
      qualityCheck: { status: "Continuous", lastScore: "96%", nextCheck: "Ongoing" }
    },
    lat: 25.37,
    lng: 72.52,
    region: "rajasthan"
  },
  {
    id: 4,
    name: "Golden Valley Vineyards",
    location: "Nashik, Maharashtra",
    farmer: "Prakash Deshmukh",
    crops: [
      { name: "Royal Pomegranate", price: "$7.50 - $11.50/kg", grade: "A++" },
      { name: "Premium Grapes", price: "$6.00 - $9.00/kg", grade: "A+" },
      { name: "Golden Onion", price: "$2.50 - $4.00/kg", grade: "A" }
    ],
    area: "60 acres",
    established: "2015",
    certifications: ["ISO 22000", "HACCP", "GlobalGAP", "BRC"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Stable climatic conditions. Yield forecast 25% above average. Perfect for bulk export contracts.",
    exportReadiness: "Ready – Long Term Contracts Active",
    monthlyProduction: "3.5 tons",
    annualRevenue: "$710,000",
    sustainabilityScore: 89,
    waterUsageEfficiency: "88%",
    carbonFootprint: "Medium",
    marketDemand: "High",
    priceRange: "$7.50 - $11.50/kg",
    weatherCondition: "partly-cloudy",
    qualityTrend: [91, 92, 90, 93, 94, 92, 93],
    soilPH: 6.7,
    rainfall: 120,
    premiumLevel: "Platinum",
    exportMarkets: ["UAE", "UK", "Netherlands", "Russia"],
    nearestPort: "Mumbai Port",
    shippingRoute: [[19.99, 73.78], [19.0760, 72.8777]],
    shippingDuration: "1-2 days to port",
    roiData: {
      investmentRequired: "$250,000",
      expectedReturn: "$710,000",
      profitMargin: "184%",
      paybackPeriod: "4-6 months",
      annualROI: "284%"
    },
    farmerControls: {
      irrigation: { status: "Smart System", schedule: "Every 36h", automation: "90%" },
      pestControl: { status: "Monitoring", lastSpray: "4 days ago", method: "Integrated" },
      harvesting: { status: "Scheduled", date: "18 days", equipment: "Modern" },
      qualityCheck: { status: "Twice Daily", lastScore: "93%", nextCheck: "Today PM" }
    },
    lat: 19.99,
    lng: 73.78,
    region: "maharashtra"
  },
  {
    id: 5,
    name: "Royal Spice Hills",
    location: "Coorg, Karnataka",
    farmer: "Ravi Gowda",
    crops: [
      { name: "Premium Coffee", price: "$25.00 - $45.00/kg", grade: "Elite" },
      { name: "Royal Cardamom", price: "$35.00 - $60.00/kg", grade: "A++" },
      { name: "Golden Black Pepper", price: "$12.00 - $18.00/kg", grade: "A+" }
    ],
    area: "40 acres",
    established: "2014",
    certifications: ["Organic", "Rainforest Alliance", "Fair Trade", "Kosher"],
    status: "healthy",
    exportGrade: "Elite Grade",
    aiInsights: "Perfect humidity and shade coverage. Ideal for specialty premium exports with high aroma scores.",
    exportReadiness: "Elite Export Ready",
    monthlyProduction: "1.8 tons",
    annualRevenue: "$745,000",
    sustainabilityScore: 92,
    waterUsageEfficiency: "91%",
    carbonFootprint: "Low",
    marketDemand: "High",
    priceRange: "$25.00 - $60.00/kg",
    weatherCondition: "misty",
    qualityTrend: [94, 95, 94, 96, 97, 95, 96],
    soilPH: 5.8,
    rainfall: 320,
    premiumLevel: "Diamond",
    exportMarkets: ["USA", "Germany", "Japan", "Switzerland", "UK"],
    nearestPort: "Cochin Port",
    shippingRoute: [[12.40, 75.74], [9.9312, 76.2673]],
    shippingDuration: "1-2 days to port",
    roiData: {
      investmentRequired: "$180,000",
      expectedReturn: "$745,000",
      profitMargin: "314%",
      paybackPeriod: "3-4 months",
      annualROI: "414%"
    },
    farmerControls: {
      irrigation: { status: "Natural Rainfall", schedule: "Seasonal", automation: "40%" },
      pestControl: { status: "Preventive", lastSpray: "7 days ago", method: "Organic" },
      harvesting: { status: "Selective", date: "25 days", equipment: "Manual" },
      qualityCheck: { status: "Daily", lastScore: "97%", nextCheck: "Ongoing" }
    },
    lat: 12.40,
    lng: 75.74,
    region: "karnataka"
  },
  {
    id: 6,
    name: "Solapur Spice Shield",
    location: "Solapur, Maharashtra",
    farmer: "Sunita Patil",
    crops: [
      { name: "Golden Turmeric", price: "$5.80 - $8.90/kg", grade: "Premium A" },
      { name: "Royal Pomegranate", price: "$7.00 - $10.50/kg", grade: "A+" },
      { name: "Premium Cotton", price: "$3.50 - $5.50/kg", grade: "A" }
    ],
    area: "50 acres",
    established: "2016",
    certifications: ["ISO 22000", "Organic in Conversion", "HACCP"],
    status: "warning",
    exportGrade: "Premium A",
    aiInsights: "Heat-wave conditions monitored. AI recommends optimized irrigation windows and shade management.",
    exportReadiness: "Export Ready – Under Weather Watch",
    monthlyProduction: "2.7 tons",
    annualRevenue: "$445,000",
    sustainabilityScore: 82,
    waterUsageEfficiency: "84%",
    carbonFootprint: "Medium",
    marketDemand: "Medium",
    priceRange: "$5.80 - $10.50/kg",
    weatherCondition: "sunny",
    qualityTrend: [88, 86, 85, 87, 84, 85, 86],
    soilPH: 7.0,
    rainfall: 45,
    premiumLevel: "Gold",
    exportMarkets: ["UAE", "Oman", "Qatar", "Bahrain"],
    nearestPort: "Mumbai Port",
    shippingRoute: [[17.68, 75.92], [19.0760, 72.8777]],
    shippingDuration: "3-4 days to port",
    roiData: {
      investmentRequired: "$175,000",
      expectedReturn: "$445,000",
      profitMargin: "154%",
      paybackPeriod: "5-6 months",
      annualROI: "254%"
    },
    farmerControls: {
      irrigation: { status: "Emergency Mode", schedule: "Every 72h", automation: "65%" },
      pestControl: { status: "Active", lastSpray: "1 day ago", method: "Chemical" },
      harvesting: { status: "Delayed", date: "30 days", equipment: "Standard" },
      qualityCheck: { status: "Daily", lastScore: "86%", nextCheck: "Today" }
    },
    lat: 17.68,
    lng: 75.92,
    region: "maharashtra"
  },
  {
    id: 7,
    name: "Idukki Royal Spice Estate",
    location: "Idukki, Kerala",
    farmer: "Thomas Mathew",
    crops: [
      { name: "Premium Cardamom", price: "$45.00 - $75.00/kg", grade: "World Class" },
      { name: "Royal Black Pepper", price: "$15.00 - $25.00/kg", grade: "A++" },
      { name: "Golden Nutmeg", price: "$20.00 - $35.00/kg", grade: "A+" }
    ],
    area: "35 acres",
    established: "2013",
    certifications: ["Organic", "ISO 22000", "Fair Trade", "EU Organic", "USDA"],
    status: "healthy",
    exportGrade: "World Class",
    aiInsights: "Premium essential oil content and colour profile detected by AI quality sensors. Perfect for European markets.",
    exportReadiness: "World Class Export Ready",
    monthlyProduction: "1.5 tons",
    annualRevenue: "$760,000",
    sustainabilityScore: 95,
    waterUsageEfficiency: "93%",
    carbonFootprint: "Low",
    marketDemand: "Very High",
    priceRange: "$15.00 - $75.00/kg",
    weatherCondition: "rainy",
    qualityTrend: [96, 97, 96, 98, 97, 96, 97],
    soilPH: 5.5,
    rainfall: 450,
    premiumLevel: "Diamond",
    exportMarkets: ["Germany", "France", "UK", "USA", "Japan"],
    nearestPort: "Cochin Port",
    shippingRoute: [[9.85, 76.97], [9.9312, 76.2673]],
    shippingDuration: "1-2 days to port",
    roiData: {
      investmentRequired: "$220,000",
      expectedReturn: "$760,000",
      profitMargin: "245%",
      paybackPeriod: "3-5 months",
      annualROI: "345%"
    },
    farmerControls: {
      irrigation: { status: "Natural Moisture", schedule: "Rain Dependent", automation: "20%" },
      pestControl: { status: "Natural Predators", lastSpray: "Never", method: "Organic" },
      harvesting: { status: "Selective", date: "10 days", equipment: "Traditional" },
      qualityCheck: { status: "Continuous", lastScore: "98%", nextCheck: "Ongoing" }
    },
    lat: 9.85,
    lng: 76.97,
    region: "kerala"
  },
  {
    id: 8,
    name: "Unjha Sustainable Spice Fields",
    location: "Unjha, Gujarat",
    farmer: "Kiran Patel",
    crops: [
      { name: "Premium Cumin", price: "$7.00 - $10.00/kg", grade: "A+" },
      { name: "Golden Fennel", price: "$6.50 - $9.50/kg", grade: "A" },
      { name: "Royal Mustard Seeds", price: "$4.00 - $6.50/kg", grade: "A" }
    ],
    area: "47 acres",
    established: "2020",
    certifications: ["ISO 22000", "HACCP", "Halal"],
    status: "warning",
    exportGrade: "Grade A",
    aiInsights: "Dry conditions affecting growth. Climate control systems for stabilization. AI recommends drip irrigation optimization.",
    exportReadiness: "Quality Monitoring",
    monthlyProduction: "2.0 tons",
    annualRevenue: "$325,000",
    sustainabilityScore: 79,
    waterUsageEfficiency: "82%",
    carbonFootprint: "Medium",
    marketDemand: "Medium",
    priceRange: "$4.00 - $10.00/kg",
    weatherCondition: "sunny",
    qualityTrend: [85, 84, 83, 85, 84, 82, 84],
    soilPH: 7.2,
    rainfall: 35,
    premiumLevel: "Gold",
    exportMarkets: ["UAE", "Saudi Arabia", "Kuwait", "Oman"],
    nearestPort: "Mundra Port",
    shippingRoute: [[23.80, 72.40], [22.6989, 69.7581]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$140,000",
      expectedReturn: "$325,000",
      profitMargin: "132%",
      paybackPeriod: "6-8 months",
      annualROI: "232%"
    },
    farmerControls: {
      irrigation: { status: "Drip System", schedule: "Every 96h", automation: "75%" },
      pestControl: { status: "Monitoring", lastSpray: "4 days ago", method: "Integrated" },
      harvesting: { status: "Optimizing", date: "22 days", equipment: "Modern" },
      qualityCheck: { status: "Every 2 Days", lastScore: "84%", nextCheck: "Tomorrow" }
    },
    lat: 23.80,
    lng: 72.40,
    region: "gujarat"
  },
  {
    id: 9,
    name: "Mysore Spice Heritage",
    location: "Mysore, Karnataka",
    farmer: "Kavitha Rao",
    crops: [
      { name: "Premium Cardamom", price: "$40.00 - $70.00/kg", grade: "A++" },
      { name: "Royal Black Pepper", price: "$14.00 - $22.00/kg", grade: "A+" },
      { name: "Golden Vanilla", price: "$50.00 - $90.00/kg", grade: "World Class" }
    ],
    area: "38 acres",
    established: "2015",
    certifications: ["Organic", "ISO 22000", "Fair Trade", "Rainforest Alliance"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Premium spice quality detected. High market value expected. Perfect for luxury food industry.",
    exportReadiness: "Premium Export Ready",
    monthlyProduction: "1.2 tons",
    annualRevenue: "$650,000",
    sustainabilityScore: 90,
    waterUsageEfficiency: "89%",
    carbonFootprint: "Low",
    marketDemand: "Very High",
    priceRange: "$14.00 - $90.00/kg",
    weatherCondition: "cloudy",
    qualityTrend: [93, 94, 93, 95, 94, 93, 94],
    soilPH: 5.9,
    rainfall: 280,
    premiumLevel: "Diamond",
    exportMarkets: ["USA", "France", "UK", "Japan", "Australia"],
    nearestPort: "Chennai Port",
    shippingRoute: [[12.2958, 76.6394], [13.0837, 80.2700]],
    shippingDuration: "3-4 days to port",
    roiData: {
      investmentRequired: "$160,000",
      expectedReturn: "$650,000",
      profitMargin: "306%",
      paybackPeriod: "3-4 months",
      annualROI: "406%"
    },
    farmerControls: {
      irrigation: { status: "Micro-sprinkler", schedule: "Every 48h", automation: "80%" },
      pestControl: { status: "Natural", lastSpray: "10 days ago", method: "Organic" },
      harvesting: { status: "Selective", date: "15 days", equipment: "Premium" },
      qualityCheck: { status: "Daily", lastScore: "95%", nextCheck: "Today" }
    },
    lat: 12.2958,
    lng: 76.6394,
    region: "karnataka"
  },
  {
    id: 10,
    name: "Punjab Golden Fields",
    location: "Amritsar, Punjab",
    farmer: "Harpreet Singh",
    crops: [
      { name: "Premium Basmati Rice", price: "$4.50 - $7.50/kg", grade: "A++" },
      { name: "Golden Wheat", price: "$2.80 - $4.20/kg", grade: "A+" },
      { name: "Royal Maize", price: "$2.20 - $3.80/kg", grade: "A" }
    ],
    area: "75 acres",
    established: "2012",
    certifications: ["ISO 22000", "HACCP", "Organic", "Halal"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Optimal soil conditions with high mineral content. Perfect for premium grain exports. AI predicts record harvest.",
    exportReadiness: "Ready for Bulk Export",
    monthlyProduction: "5.0 tons",
    annualRevenue: "$580,000",
    sustainabilityScore: 87,
    waterUsageEfficiency: "85%",
    carbonFootprint: "Medium",
    marketDemand: "High",
    priceRange: "$2.20 - $7.50/kg",
    weatherCondition: "sunny",
    qualityTrend: [91, 92, 90, 93, 92, 91, 92],
    soilPH: 6.5,
    rainfall: 65,
    premiumLevel: "Platinum",
    exportMarkets: ["UAE", "Saudi Arabia", "USA", "UK", "Canada"],
    nearestPort: "Mumbai Port",
    shippingRoute: [[31.6340, 74.8723], [19.0760, 72.8777]],
    shippingDuration: "4-5 days to port",
    roiData: {
      investmentRequired: "$300,000",
      expectedReturn: "$580,000",
      profitMargin: "93%",
      paybackPeriod: "6-8 months",
      annualROI: "193%"
    },
    farmerControls: {
      irrigation: { status: "Canal System", schedule: "Weekly", automation: "60%" },
      pestControl: { status: "Integrated", lastSpray: "6 days ago", method: "Balanced" },
      harvesting: { status: "Mechanized", date: "8 days", equipment: "Advanced" },
      qualityCheck: { status: "Daily", lastScore: "92%", nextCheck: "Today" }
    },
    lat: 31.6340,
    lng: 74.8723,
    region: "punjab"
  },
  {
    id: 11,
    name: "Madhya Pradesh Organic Oasis",
    location: "Indore, Madhya Pradesh",
    farmer: "Vikram Jain",
    crops: [
      { name: "Premium Soybean", price: "$3.50 - $5.50/kg", grade: "A+" },
      { name: "Golden Wheat", price: "$2.50 - $4.00/kg", grade: "A" },
      { name: "Royal Maize", price: "$2.00 - $3.50/kg", grade: "A" }
    ],
    area: "65 acres",
    established: "2019",
    certifications: ["Organic", "ISO 22000", "HACCP", "Non-GMO"],
    status: "healthy",
    exportGrade: "Premium A+",
    aiInsights: "Optimal crop rotation system detected. Soil fertility at peak levels. Perfect for organic export markets.",
    exportReadiness: "Organic Export Ready",
    monthlyProduction: "4.2 tons",
    annualRevenue: "$390,000",
    sustainabilityScore: 92,
    waterUsageEfficiency: "88%",
    carbonFootprint: "Low",
    marketDemand: "High",
    priceRange: "$2.00 - $5.50/kg",
    weatherCondition: "partly-cloudy",
    qualityTrend: [89, 90, 88, 91, 90, 89, 90],
    soilPH: 6.8,
    rainfall: 95,
    premiumLevel: "Platinum",
    exportMarkets: ["USA", "Germany", "UK", "Japan"],
    nearestPort: "Mumbai Port",
    shippingRoute: [[22.7196, 75.8577], [19.0760, 72.8777]],
    shippingDuration: "3-4 days to port",
    roiData: {
      investmentRequired: "$220,000",
      expectedReturn: "$390,000",
      profitMargin: "77%",
      paybackPeriod: "7-9 months",
      annualROI: "177%"
    },
    farmerControls: {
      irrigation: { status: "Sprinkler", schedule: "Every 72h", automation: "70%" },
      pestControl: { status: "Organic Only", lastSpray: "8 days ago", method: "Natural" },
      harvesting: { status: "Scheduled", date: "20 days", equipment: "Modern" },
      qualityCheck: { status: "Daily", lastScore: "90%", nextCheck: "Today" }
    },
    lat: 22.7196,
    lng: 75.8577,
    region: "madhya pradesh"
  },
  {
    id: 12,
    name: "Tamil Nadu Spice Heritage",
    location: "Madurai, Tamil Nadu",
    farmer: "Murugan Selvam",
    crops: [
      { name: "Premium Cardamom", price: "$35.00 - $65.00/kg", grade: "A++" },
      { name: "Royal Cinnamon", price: "$12.00 - $18.00/kg", grade: "A+" },
      { name: "Golden Cloves", price: "$8.00 - $14.00/kg", grade: "A" }
    ],
    area: "43 acres",
    established: "2016",
    certifications: ["Organic", "ISO 22000", "Fair Trade", "Kosher"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Optimal spice oil development. Premium grade confirmed. Ideal for European specialty markets.",
    exportReadiness: "Premium Export Ready",
    monthlyProduction: "1.6 tons",
    annualRevenue: "$530,000",
    sustainabilityScore: 91,
    waterUsageEfficiency: "87%",
    carbonFootprint: "Low",
    marketDemand: "High",
    priceRange: "$8.00 - $65.00/kg",
    weatherCondition: "partly-cloudy",
    qualityTrend: [92, 93, 91, 94, 93, 92, 93],
    soilPH: 6.2,
    rainfall: 180,
    premiumLevel: "Diamond",
    exportMarkets: ["USA", "Germany", "France", "UK", "Netherlands"],
    nearestPort: "Chennai Port",
    shippingRoute: [[9.9252, 78.1198], [13.0837, 80.2700]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$150,000",
      expectedReturn: "$530,000",
      profitMargin: "253%",
      paybackPeriod: "3-5 months",
      annualROI: "353%"
    },
    farmerControls: {
      irrigation: { status: "Micro-irrigation", schedule: "Every 48h", automation: "85%" },
      pestControl: { status: "Preventive", lastSpray: "5 days ago", method: "Organic" },
      harvesting: { status: "Selective", date: "18 days", equipment: "Traditional" },
      qualityCheck: { status: "Daily", lastScore: "94%", nextCheck: "Today" }
    },
    lat: 9.9252,
    lng: 78.1198,
    region: "tamil nadu"
  },
  {
    id: 13,
    name: "Andhra Spice Valley",
    location: "Guntur, Andhra Pradesh",
    farmer: "Venkat Reddy",
    crops: [
      { name: "Premium Red Chili", price: "$5.00 - $8.50/kg", grade: "A+" },
      { name: "Golden Turmeric", price: "$4.80 - $7.20/kg", grade: "A" },
      { name: "Royal Coriander", price: "$4.20 - $6.50/kg", grade: "A" }
    ],
    area: "55 acres",
    established: "2018",
    certifications: ["ISO 22000", "HACCP", "Halal"],
    status: "healthy",
    exportGrade: "Premium A+",
    aiInsights: "High capsaicin levels in chilies. Export quality maintained. Perfect for Middle Eastern markets.",
    exportReadiness: "Export Ready",
    monthlyProduction: "3.2 tons",
    annualRevenue: "$425,000",
    sustainabilityScore: 86,
    waterUsageEfficiency: "83%",
    carbonFootprint: "Medium",
    marketDemand: "High",
    priceRange: "$4.20 - $8.50/kg",
    weatherCondition: "sunny",
    qualityTrend: [88, 89, 87, 90, 89, 88, 89],
    soilPH: 7.0,
    rainfall: 85,
    premiumLevel: "Gold",
    exportMarkets: ["UAE", "Saudi Arabia", "Kuwait", "Qatar", "Oman"],
    nearestPort: "Chennai Port",
    shippingRoute: [[16.3067, 80.4365], [13.0837, 80.2700]],
    shippingDuration: "2-3 days to port",
    roiData: {
      investmentRequired: "$180,000",
      expectedReturn: "$425,000",
      profitMargin: "136%",
      paybackPeriod: "5-7 months",
      annualROI: "236%"
    },
    farmerControls: {
      irrigation: { status: "Drip System", schedule: "Every 72h", automation: "75%" },
      pestControl: { status: "Active", lastSpray: "3 days ago", method: "Integrated" },
      harvesting: { status: "Ready", date: "25 days", equipment: "Modern" },
      qualityCheck: { status: "Daily", lastScore: "89%", nextCheck: "Today" }
    },
    lat: 16.3067,
    lng: 80.4365,
    region: "andhra pradesh"
  },
  {
    id: 14,
    name: "Uttar Pradesh Mega Farm",
    location: "Lucknow, Uttar Pradesh",
    farmer: "Amit Sharma",
    crops: [
      { name: "Premium Basmati Rice", price: "$5.00 - $8.00/kg", grade: "A++" },
      { name: "Golden Sugarcane", price: "$1.50 - $2.50/kg", grade: "A+" },
      { name: "Royal Wheat", price: "$2.80 - $4.20/kg", grade: "A" }
    ],
    area: "85 acres",
    established: "2014",
    certifications: ["ISO 22000", "HACCP", "Organic", "Halal"],
    status: "healthy",
    exportGrade: "Premium A++",
    aiInsights: "Massive scale production with excellent quality control. Ideal for large international contracts.",
    exportReadiness: "Ready for Bulk Orders",
    monthlyProduction: "6.5 tons",
    annualRevenue: "$850,000",
    sustainabilityScore: 84,
    waterUsageEfficiency: "86%",
    carbonFootprint: "Medium",
    marketDemand: "High",
    priceRange: "$1.50 - $8.00/kg",
    weatherCondition: "sunny",
    qualityTrend: [90, 91, 89, 92, 91, 90, 91],
    soilPH: 6.9,
    rainfall: 110,
    premiumLevel: "Platinum",
    exportMarkets: ["UAE", "Saudi Arabia", "USA", "UK", "Canada", "Australia"],
    nearestPort: "Mundra Port",
    shippingRoute: [[26.8467, 80.9462], [22.6989, 69.7581]],
    shippingDuration: "5-6 days to port",
    roiData: {
      investmentRequired: "$400,000",
      expectedReturn: "$850,000",
      profitMargin: "113%",
      paybackPeriod: "5-7 months",
      annualROI: "213%"
    },
    farmerControls: {
      irrigation: { status: "Canal System", schedule: "Weekly", automation: "65%" },
      pestControl: { status: "Integrated", lastSpray: "5 days ago", method: "Balanced" },
      harvesting: { status: "Mechanized", date: "12 days", equipment: "Large Scale" },
      qualityCheck: { status: "Continuous", lastScore: "91%", nextCheck: "Ongoing" }
    },
    lat: 26.8467,
    lng: 80.9462,
    region: "uttar pradesh"
  }
];

// Function to get random variations for simulation
export const getRandomFarmVariations = (visitId) => {
  return ENHANCED_FARMS.map(farm => {
    const variationFactor = 0.9 + (visitId % 10) * 0.02;
    
    return {
      ...farm,
      temperature: 28 + Math.random() * 8 * variationFactor,
      humidity: 50 + Math.random() * 20 * variationFactor,
      soilMoisture: 70 + Math.random() * 15 * variationFactor,
      cropHealth: 85 + Math.random() * 10 * variationFactor,
      qualityScore: 90 + Math.random() * 8 * variationFactor,
      sustainabilityScore: Math.min(100, farm.sustainabilityScore + (Math.random() - 0.5) * 5),
      waterUsageEfficiency: `${Math.min(100, parseInt(farm.waterUsageEfficiency) + (Math.random() - 0.5) * 3)}%`,
      qualityTrend: farm.qualityTrend.map(score => 
        Math.min(100, score + (Math.random() - 0.5) * 2)
      )
    };
  });
};

// Export default
export default ENHANCED_FARMS;