// src/utils/PDFGenerator.js
import jsPDF from 'jspdf';
import 'jspdf-autotable';

class PDFGenerator {
  constructor() {
    this.margin = 15;
    this.pageWidth = 210;
    this.pageHeight = 297;
  }

  // Professional number formatting
  formatNumber(value, currency = 'INR') {
    if (!value && value !== 0) return '0.00';
    
    if (currency === 'INR') {
      // Indian numbering system
      const parts = value.toFixed(2).split('.');
      parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');
      return parts.join('.');
    } else {
      // International numbering
      return value.toLocaleString('en-US', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      });
    }
  }

  getCurrencySymbol(currency) {
    const symbols = {
      'INR': '₹',
      'USD': '$',
      'EUR': '€',
      'GBP': '£',
      'AED': 'AED ',
      'SAR': 'SAR '
    };
    return symbols[currency] || currency;
  }

  // Professional header for all documents
  addProfessionalHeader(doc, title, documentNumber, issueDate) {
    // Blue header background
    doc.setFillColor(41, 128, 185);
    doc.rect(0, 0, this.pageWidth, 25, 'F');
    
    // Company name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SAFFRON EMPORIAL', this.margin, 15);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Export Excellence Since 2023', this.margin, 21);

    // Document title
    doc.setTextColor(41, 128, 185);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title.toUpperCase(), this.pageWidth / 2, 45, { align: 'center' });

    // Document details
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text(`Document No: ${documentNumber}`, this.pageWidth - this.margin, 35, { align: 'right' });
    doc.text(`Issue Date: ${issueDate}`, this.pageWidth - this.margin, 40, { align: 'right' });

    // Separator
    doc.setDrawColor(200, 200, 200);
    doc.line(this.margin, 50, this.pageWidth - this.margin, 50);

    return 55;
  }

  // Professional footer
  addProfessionalFooter(doc) {
    const footerY = this.pageHeight - 15;
    
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Saffron Emporial Export Management System', this.pageWidth / 2, footerY - 10, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')} at ${new Date().toLocaleTimeString('en-IN')}`, this.pageWidth / 2, footerY - 5, { align: 'center' });
  }

  // Generate Sales Invoice PDF
  generateSalesInvoice(documentData, documentNumber) {
    const doc = new jsPDF();
    const currency = documentData.totals?.currency || 'INR';
    const currencySymbol = this.getCurrencySymbol(currency);
    
    let y = this.addProfessionalHeader(
      doc, 
      'COMMERCIAL INVOICE', 
      documentNumber, 
      documentData.invoiceDate || new Date().toISOString().split('T')[0]
    );

    // Exporter & Consignee Information
    const colWidth = (this.pageWidth - (this.margin * 2) - 10) / 2;

    // Exporter
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('EXPORTER:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.exporter?.legalName || documentData.exporter?.name || 'Exporter Name', this.margin, y + 6);
    
    const exporterAddress = doc.splitTextToSize(
      documentData.exporter?.registeredAddress || documentData.exporter?.address || 'Exporter Address', 
      colWidth
    );
    exporterAddress.forEach((line, index) => {
      doc.text(line, this.margin, y + 12 + (index * 4));
    });
    
    let addressHeight = exporterAddress.length * 4;
    const exporterDetailsY = y + 16 + addressHeight;
    
    doc.text(`GSTIN: ${documentData.exporter?.gstin || documentData.exporter?.taxId || 'Not provided'}`, this.margin, exporterDetailsY);
    doc.text(`IEC: ${documentData.exporter?.iecCode || 'Not provided'}`, this.margin, exporterDetailsY + 5);
    doc.text(`Phone: ${documentData.exporter?.phone || 'Not provided'}`, this.margin, exporterDetailsY + 10);
    doc.text(`Email: ${documentData.exporter?.email || 'Not provided'}`, this.margin, exporterDetailsY + 15);

    // Consignee
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('CONSIGNEE:', this.margin + colWidth + 10, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.consignee?.legalName || documentData.consignee?.name || 'Consignee Name', this.margin + colWidth + 10, y + 6);
    
    const consigneeAddress = doc.splitTextToSize(
      documentData.consignee?.address || 'Consignee Address', 
      colWidth
    );
    consigneeAddress.forEach((line, index) => {
      doc.text(line, this.margin + colWidth + 10, y + 12 + (index * 4));
    });
    
    let consigneeAddressHeight = consigneeAddress.length * 4;
    const consigneeDetailsY = y + 16 + consigneeAddressHeight;
    
    doc.text(`Tax ID: ${documentData.consignee?.taxId || 'Not provided'}`, this.margin + colWidth + 10, consigneeDetailsY);
    doc.text(`Country: ${documentData.consignee?.country || 'Not provided'}`, this.margin + colWidth + 10, consigneeDetailsY + 5);

    y += Math.max(addressHeight, consigneeAddressHeight) + 40;

    // Shipment Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SHIPMENT DETAILS:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Port of Loading: ${documentData.shipment?.portOfLoading || 'Not specified'}`, this.margin, y + 8);
    doc.text(`Port of Discharge: ${documentData.shipment?.portOfDischarge || 'Not specified'}`, this.margin + 70, y + 8);
    doc.text(`Incoterm: ${documentData.shipment?.incoterm || 'Not specified'}`, this.margin, y + 16);
    doc.text(`Payment Terms: ${documentData.shipment?.paymentTerms || 'Not specified'}`, this.margin + 70, y + 16);

    y += 25;

    // Products Table
    const tableColumns = [
      'Description',
      'HS Code', 
      'Quantity',
      'Unit',
      `Unit Price (${currencySymbol})`,
      `Amount (${currencySymbol})`
    ];

    const tableData = (documentData.products || []).map(product => [
      product.description || 'Product',
      product.hsCode || 'N/A',
      this.formatNumber(product.quantity || 0, currency),
      product.unit || 'PCS',
      this.formatNumber(product.unitPrice || 0, currency),
      this.formatNumber(product.totalPrice || 0, currency)
    ]);

    doc.autoTable({
      startY: y,
      head: [tableColumns],
      body: tableData,
      margin: { left: this.margin, right: this.margin },
      styles: { 
        fontSize: 8, 
        cellPadding: 3,
        textColor: [0, 0, 0]
      },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      theme: 'grid'
    });

    y = doc.lastAutoTable.finalY + 10;

    // Totals Section
    const totals = documentData.totals || {};
    const totalsStartX = this.pageWidth - this.margin - 80;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SUMMARY:', totalsStartX, y);
    
    doc.setFont('helvetica', 'normal');
    let currentY = y + 8;

    const totalItems = [
      { label: 'Subtotal:', value: totals.subtotal },
      { label: 'Insurance:', value: totals.insurance },
      { label: 'Freight:', value: totals.freight },
      { label: 'Other Charges:', value: totals.otherCharges }
    ];

    totalItems.forEach(item => {
      if (item.value || item.value === 0) {
        doc.text(item.label, totalsStartX, currentY);
        doc.text(`${currencySymbol}${this.formatNumber(item.value, currency)}`, this.pageWidth - this.margin, currentY, { align: 'right' });
        currentY += 8;
      }
    });

    // Grand Total
    doc.setFont('helvetica', 'bold');
    doc.text('GRAND TOTAL:', totalsStartX, currentY);
    doc.text(`${currencySymbol}${this.formatNumber(totals.grandTotal || 0, currency)}`, this.pageWidth - this.margin, currentY, { align: 'right' });

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Currency: ${currency}`, this.pageWidth - this.margin, currentY + 10, { align: 'right' });

    y = currentY + 20;

    // Declaration
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('DECLARATION:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const declaration = documentData.declaration || 
      'We hereby declare that the above stated particulars are true and correct and that the goods are of Indian origin. All the goods are in accordance with the Export Policy of India.';
    
    const declarationLines = doc.splitTextToSize(declaration, this.pageWidth - (this.margin * 2));
    declarationLines.forEach((line, index) => {
      doc.text(line, this.margin, y + 8 + (index * 4));
    });

    y += declarationLines.length * 4 + 20;

    // Signatures
    doc.setFontSize(10);
    doc.text('_________________________', this.margin, y);
    doc.text('Authorized Signature', this.margin, y + 6);
    doc.text(documentData.exporter?.legalName || documentData.exporter?.name || 'Exporter', this.margin, y + 12);

    doc.text('_________________________', this.pageWidth - this.margin - 60, y);
    doc.text('Authorized Signature', this.pageWidth - this.margin - 60, y + 6);
    doc.text(documentData.consignee?.legalName || documentData.consignee?.name || 'Consignee', this.pageWidth - this.margin - 60, y + 12);

    this.addProfessionalFooter(doc);
    return doc;
  }

  // Generate Packing List PDF
  generatePackingList(documentData, documentNumber) {
    const doc = new jsPDF();
    
    let y = this.addProfessionalHeader(
      doc,
      'PACKING LIST', 
      documentNumber, 
      documentData.invoiceDate || new Date().toISOString().split('T')[0]
    );

    // Company Information
    const colWidth = (this.pageWidth - (this.margin * 2) - 10) / 2;

    // Exporter
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('EXPORTER:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.exporter?.legalName || documentData.exporter?.name || 'Exporter Name', this.margin, y + 6);
    
    const exporterAddress = doc.splitTextToSize(
      documentData.exporter?.registeredAddress || documentData.exporter?.address || 'Exporter Address', 
      colWidth
    );
    exporterAddress.forEach((line, index) => {
      doc.text(line, this.margin, y + 12 + (index * 4));
    });

    // Consignee
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('CONSIGNEE:', this.margin + colWidth + 10, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.consignee?.legalName || documentData.consignee?.name || 'Consignee Name', this.margin + colWidth + 10, y + 6);
    
    const consigneeAddress = doc.splitTextToSize(
      documentData.consignee?.address || 'Consignee Address', 
      colWidth
    );
    consigneeAddress.forEach((line, index) => {
      doc.text(line, this.margin + colWidth + 10, y + 12 + (index * 4));
    });

    y += Math.max(exporterAddress.length, consigneeAddress.length) * 4 + 25;

    // Packages Table
    const tableColumns = [
      'Package No.',
      'Description', 
      'Quantity',
      'Net Weight (kg)',
      'Gross Weight (kg)',
      'Dimensions',
      'Marks'
    ];

    const tableData = (documentData.packages || []).map(pkg => [
      pkg.packageNumber || '1',
      pkg.description || 'Package',
      this.formatNumber(pkg.quantity || 0, 'INR'),
      this.formatNumber(pkg.netWeight || 0, 'INR'),
      this.formatNumber(pkg.grossWeight || 0, 'INR'),
      pkg.dimensions || 'N/A',
      pkg.marks || 'N/A'
    ]);

    doc.autoTable({
      startY: y,
      head: [tableColumns],
      body: tableData,
      margin: { left: this.margin, right: this.margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      theme: 'grid'
    });

    y = doc.lastAutoTable.finalY + 10;

    // Package Summary
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('PACKAGE SUMMARY:', this.margin, y);
    
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Packages: ${documentData.totalPackages || documentData.packages?.length || 0}`, this.margin, y + 8);
    doc.text(`Total Net Weight: ${this.formatNumber(documentData.totalNetWeight || 0, 'INR')} kg`, this.margin, y + 16);
    doc.text(`Total Gross Weight: ${this.formatNumber(documentData.totalGrossWeight || 0, 'INR')} kg`, this.margin, y + 24);

    if (documentData.containerNumber) {
      doc.text(`Container No: ${documentData.containerNumber}`, this.margin, y + 32);
    }
    if (documentData.sealNumber) {
      doc.text(`Seal No: ${documentData.sealNumber}`, this.margin, y + 40);
    }

    this.addProfessionalFooter(doc);
    return doc;
  }

  // Generate other document types with similar professional structure
  generateCommercialInvoice(documentData, documentNumber) {
    return this.generateSalesInvoice(documentData, documentNumber);
  }

  generateCertificateOfOrigin(documentData, documentNumber) {
    const doc = new jsPDF();
    
    let y = this.addProfessionalHeader(
      doc,
      'CERTIFICATE OF ORIGIN', 
      documentNumber, 
      documentData.certificateDate || new Date().toISOString().split('T')[0]
    );

    // Certificate Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('CERTIFICATE DETAILS:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Issuing Authority: ${documentData.issuingAuthority || 'Chamber of Commerce'}`, this.margin, y + 8);
    doc.text(`Origin Criteria: ${documentData.originCriteria || 'Wholly Obtained'}`, this.margin, y + 16);
    doc.text(`Certificate Date: ${documentData.certificateDate || new Date().toISOString().split('T')[0]}`, this.margin, y + 24);

    y += 35;

    // Company Information (similar to other documents)
    const colWidth = (this.pageWidth - (this.margin * 2) - 10) / 2;

    // Exporter
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('EXPORTER:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.exporter?.legalName || documentData.exporter?.name || 'Exporter Name', this.margin, y + 6);
    
    const exporterAddress = doc.splitTextToSize(
      documentData.exporter?.registeredAddress || documentData.exporter?.address || 'Exporter Address', 
      colWidth
    );
    exporterAddress.forEach((line, index) => {
      doc.text(line, this.margin, y + 12 + (index * 4));
    });

    // Consignee
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('CONSIGNEE:', this.margin + colWidth + 10, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.consignee?.legalName || documentData.consignee?.name || 'Consignee Name', this.margin + colWidth + 10, y + 6);
    
    const consigneeAddress = doc.splitTextToSize(
      documentData.consignee?.address || 'Consignee Address', 
      colWidth
    );
    consigneeAddress.forEach((line, index) => {
      doc.text(line, this.margin + colWidth + 10, y + 12 + (index * 4));
    });

    y += Math.max(exporterAddress.length, consigneeAddress.length) * 4 + 25;

    // Products Table for Origin
    const tableColumns = [
      'Product Description',
      'HS Code', 
      'Quantity',
      'Unit',
      'Gross Weight (kg)',
      'Origin Criteria'
    ];

    const tableData = (documentData.products || []).map(product => [
      product.description || 'Product',
      product.hsCode || 'N/A',
      this.formatNumber(product.quantity || 0, 'INR'),
      product.unit || 'PCS',
      this.formatNumber(product.grossWeight || 0, 'INR'),
      product.originCriteria || documentData.originCriteria || 'Wholly Obtained'
    ]);

    doc.autoTable({
      startY: y,
      head: [tableColumns],
      body: tableData,
      margin: { left: this.margin, right: this.margin },
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      theme: 'grid'
    });

    y = doc.lastAutoTable.finalY + 15;

    // Origin Declaration
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('ORIGIN DECLARATION:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const declaration = documentData.declaration || 
      'The undersigned hereby declares that the above mentioned goods originate entirely in India according to the applicable rules of origin.';
    
    const declarationLines = doc.splitTextToSize(declaration, this.pageWidth - (this.margin * 2));
    declarationLines.forEach((line, index) => {
      doc.text(line, this.margin, y + 8 + (index * 4));
    });

    y += declarationLines.length * 4 + 25;

    // Certification
    doc.setFontSize(10);
    doc.text('_________________________', this.margin, y);
    doc.text('Authorized Signature & Stamp', this.margin, y + 6);
    doc.text(documentData.issuingAuthority || 'Chamber of Commerce', this.margin, y + 12);

    this.addProfessionalFooter(doc);
    return doc;
  }

  generateBillOfLading(documentData, documentNumber) {
    const doc = new jsPDF();
    
    let y = this.addProfessionalHeader(
      doc,
      'BILL OF LADING', 
      documentNumber, 
      documentData.dateOfIssue || new Date().toISOString().split('T')[0]
    );

    // Shipping Information
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SHIPPING INFORMATION:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Vessel: ${documentData.vesselName || 'To be assigned'}`, this.margin, y + 8);
    doc.text(`Voyage: ${documentData.voyageNumber || 'N/A'}`, this.margin + 70, y + 8);
    doc.text(`B/L Type: ${documentData.blType || 'Original'}`, this.margin, y + 16);
    doc.text(`Container: ${documentData.containerNumber || 'To be assigned'}`, this.margin + 70, y + 16);
    doc.text(`Place of Receipt: ${documentData.placeOfReceipt || documentData.shipment?.portOfLoading || 'Not specified'}`, this.margin, y + 24);
    doc.text(`Place of Delivery: ${documentData.placeOfDelivery || documentData.shipment?.portOfDischarge || 'Not specified'}`, this.margin + 70, y + 24);

    y += 35;

    // Shipper & Consignee Information
    const colWidth = (this.pageWidth - (this.margin * 2) - 10) / 2;

    // Shipper
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('SHIPPER:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.exporter?.legalName || documentData.exporter?.name || 'Shipper Name', this.margin, y + 6);
    
    const shipperAddress = doc.splitTextToSize(
      documentData.exporter?.registeredAddress || documentData.exporter?.address || 'Shipper Address', 
      colWidth
    );
    shipperAddress.forEach((line, index) => {
      doc.text(line, this.margin, y + 12 + (index * 4));
    });

    // Consignee
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('CONSIGNEE:', this.margin + colWidth + 10, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(documentData.consignee?.legalName || documentData.consignee?.name || 'Consignee Name', this.margin + colWidth + 10, y + 6);
    
    const consigneeAddress = doc.splitTextToSize(
      documentData.consignee?.address || 'Consignee Address', 
      colWidth
    );
    consigneeAddress.forEach((line, index) => {
      doc.text(line, this.margin + colWidth + 10, y + 12 + (index * 4));
    });

    y += Math.max(shipperAddress.length, consigneeAddress.length) * 4 + 25;

    // Cargo Details
    const tableColumns = [
      'Marks & Numbers',
      'No. of Packages', 
      'Description of Goods',
      'Gross Weight (kg)',
      'Measurement (CBM)'
    ];

    const tableData = (documentData.products || []).map(product => [
      product.marks || 'N/M',
      product.numberOfPackages || 1,
      product.description || 'Goods',
      this.formatNumber(product.grossWeight || product.quantity || 0, 'INR'),
      this.formatNumber(product.measurement || 0, 'INR') || 'N/A'
    ]);

    doc.autoTable({
      startY: y,
      head: [tableColumns],
      body: tableData,
      margin: { left: this.margin, right: this.margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      theme: 'grid'
    });

    y = doc.lastAutoTable.finalY + 15;

    // Carrier's Receipt
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text("CARRIER'S RECEIPT:", this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Shipped on board in apparent good order and condition unless otherwise stated.', this.margin, y + 8);
    
    doc.text(`Number of Originals: ${documentData.numberOfOriginals || '3'}`, this.margin, y + 16);
    doc.text(`Freight: ${documentData.freightTerms || 'Prepaid'}`, this.margin, y + 21);
    doc.text(`Place of Issue: ${documentData.placeOfIssue || documentData.shipment?.portOfLoading || 'Not specified'}`, this.margin, y + 26);

    y += 35;

    // Signature
    doc.text('_________________________', this.margin, y);
    doc.text('For and on behalf of the Carrier', this.margin, y + 6);
    doc.text(documentData.carrierSignature || 'Authorized Signature', this.margin, y + 12);

    this.addProfessionalFooter(doc);
    return doc;
  }

  generateExportDeclaration(documentData, documentNumber) {
    const doc = new jsPDF();
    
    let y = this.addProfessionalHeader(
      doc,
      'EXPORT DECLARATION', 
      documentNumber, 
      documentData.declarationDate || new Date().toISOString().split('T')[0]
    );

    // Declaration Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('DECLARATION DETAILS:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Customs Office: ${documentData.customsOffice || 'JNPT Customs, Mumbai'}`, this.margin, y + 8);
    doc.text(`Declaration Type: ${documentData.declarationType || 'Free Export'}`, this.margin, y + 16);
    doc.text(`Mode of Transport: ${documentData.modeOfTransport || 'Sea'}`, this.margin, y + 24);
    doc.text(`Exporter Reference: ${documentData.exporterReference || 'N/A'}`, this.margin, y + 32);

    y += 45;

    // Exporter Information
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('EXPORTER INFORMATION:', this.margin, y);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${documentData.exporter?.legalName || documentData.exporter?.name || 'Exporter Name'}`, this.margin, y + 8);
    doc.text(`GSTIN: ${documentData.exporter?.gstin || documentData.exporter?.taxId || 'Not provided'}`, this.margin, y + 16);
    doc.text(`IEC Code: ${documentData.exporter?.iecCode || 'Not provided'}`, this.margin, y + 24);
    doc.text(`PAN: ${documentData.exporter?.panNumber || 'Not provided'}`, this.margin, y + 32);

    y += 45;

    // Commodity Details
    const tableColumns = [
      'HS Code',
      'Goods Description', 
      'Quantity',
      'Unit',
      'FOB Value (INR)',
      'Export Policy'
    ];

    const tableData = (documentData.products || []).map(product => [
      product.hsCode || 'N/A',
      product.description || 'Goods',
      this.formatNumber(product.quantity || 0, 'INR'),
      product.unit || 'KGM',
      this.formatNumber(product.fobValue || product.totalPrice || 0, 'INR'),
      product.exportPolicy || 'Free'
    ]);

    doc.autoTable({
      startY: y,
      head: [tableColumns],
      body: tableData,
      margin: { left: this.margin, right: this.margin },
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: [255, 255, 255],
        fontStyle: 'bold'
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      theme: 'grid'
    });

    y = doc.lastAutoTable.finalY + 15;

    // Legal Declaration
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('LEGAL DECLARATION:', this.margin, y);
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const legalText = documentData.customsDeclaration || 
      'I/We hereby declare that the particulars given in this declaration are true and that the export of the goods described herein is not prohibited under any law for the time being in force. I/We also declare that the goods are not being exported in violation of any order issued by the Central Government under any law for the time being in force.';
    
    const legalLines = doc.splitTextToSize(legalText, this.pageWidth - (this.margin * 2));
    legalLines.forEach((line, index) => {
      doc.text(line, this.margin, y + 8 + (index * 3.5));
    });

    y += legalLines.length * 3.5 + 20;

    // Signatory Details
    doc.setFontSize(10);
    doc.text('_________________________', this.margin, y);
    doc.text('Authorized Signatory', this.margin, y + 6);
    doc.text('Exporter', this.margin, y + 12);

    this.addProfessionalFooter(doc);
    return doc;
  }

  // Convert PDF to blob for storage
  getPDFAsBlob(pdfDoc) {
    return pdfDoc.output('blob');
  }
}

export default new PDFGenerator();